export const INIT_FETCH_PROFILE_DATA = 'INIT_FETCH_PROFILE_DATA';
export const SET_PROFILE_DATA_SUCCESS = 'SET_PROFILE_DATA_SUCCESS';
export const SET_PROFILE_DATA_ERROR = 'SET_PROFILE_DATA_ERROR';

export const UPDATE_PROFILE_DATA = 'UPDATE_PROFILE_DATA';
export const DELETE_PROFILE_DATA = 'DELETE_PROFILE_DATA';
